const K={c:"wf_c",d:"wf_d",r:"wf_r",p:"wf_p",s:"wf_s"};
const def={centers:["مطاي","بني مزار"],villages:{مطاي:["مطاي البلد","أبو عزيز","بردنوها","منبال","أبوان","إبوان","حلوة","سيلة الشرقية","سيلة الغربية","عزبة بطرس","عزبة أبو شحاته"],"بني مزار":[]},types:{غسالات:["هاف أوتوماتيك","فوق أوتوماتيك","أمامي أوتوماتيك"],ثلاجات:["عادية","نوفروست","ديب فريزر"],تكييفات:["سبليت","شباك"],سخانات:["كهرباء","غاز"],كولديرات:["كولدير"],أجهزة_أخرى:["عام"]},brands:["Fresh","Unionaire","Tornado","Beko","LG","Samsung","Sharp","Ariston","Zanussi","Whirlpool","Indesit","White Point","Kiriazi","Ideal","Fagor","Daewoo","Hitachi","Panasonic","Carrier","Midea","Haier","Gree","TCL","فريش","توشيبا العربى","كريازى"],partCats:["ثلاجات وفريزرات","غسالات","تكييف","سخانات","كهرباء وإلكترونيات","مواتير","كمبروسرات","أخرى"]};
function get(k,f=[]){try{let x=JSON.parse(localStorage.getItem(k));return x??f}catch{return f}} function put(k,v){localStorage.setItem(k,JSON.stringify(v))}
function settings(){let s=get(K.s,null);if(!s){s=def;put(K.s,s)}return s}
function arr(k){return get(k,[])} function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))} function id(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function toggle(x){document.getElementById(x)?.classList.toggle("hidden")}
function customerName(i){return arr(K.c).find(x=>x.id===i)?.name||"—"} function deviceName(i){let d=arr(K.d).find(x=>x.id===i);return d?`${d.type} - ${d.brand}`:"—"}
function addresses(c){return [{key:"main",label:"العنوان الأساسي",...c.mainAddress},...(c.extraAddress?.address?[{key:"extra",label:"العنوان الإضافي",...c.extraAddress}]:[])]}
function addressText(a){return `${a.center||""}${a.village?" - "+a.village:""}${a.address?" - "+a.address:""}${a.street?" - "+a.street:""}`}
function fillCenters(el,selected=""){if(!el)return;let s=settings();el.innerHTML='<option value="">اختر المركز</option>'+s.centers.map(x=>`<option ${x===selected?"selected":""}>${esc(x)}</option>`).join("")}
function fillVillages(el,center,selected=""){if(!el)return;let vs=settings().villages[center]||[];el.innerHTML='<option value="">اختر القرية</option>'+vs.map(x=>`<option ${x===selected?"selected":""}>${esc(x)}</option>`).join("")}
function fillCustomer(el,selected=""){if(!el)return;el.innerHTML='<option value="">اختر العميل</option>'+arr(K.c).map(x=>`<option value="${x.id}" ${x.id===selected?"selected":""}>${esc(x.name)} - ${esc(x.phone)}</option>`).join("")}
function fillAddress(el,cid,selected=""){let c=arr(K.c).find(x=>x.id===cid);if(!el){return}el.innerHTML='<option value="">اختر العنوان</option>'+(c?addresses(c).map(a=>`<option value="${a.key}" ${a.key===selected?"selected":""}>${esc(a.label)} — ${esc(addressText(a))}</option>`).join(""):"")}
function fillTypes(el,selected=""){let t=settings().types;el.innerHTML='<option value="">اختر النوع</option>'+Object.keys(t).map(x=>`<option ${x===selected?"selected":""}>${esc(x.replace("_"," "))}</option>`).join("")}
function fillCats(el,type,selected=""){let t=settings().types[type]||[];el.innerHTML='<option value="">اختر التصنيف</option>'+t.map(x=>`<option ${x===selected?"selected":""}>${esc(x)}</option>`).join("")}
function fillBrands(el,selected=""){el.innerHTML='<option value="">اختر الماركة</option>'+settings().brands.map(x=>`<option ${x===selected?"selected":""}>${esc(x)}</option>`).join("")}
function renderDash(){let el=document.getElementById("dashboard");if(!el)return;let c=arr(K.c),d=arr(K.d),r=arr(K.r),p=arr(K.p),open=r.filter(x=>x.status!=="مكتمل"&&x.status!=="ملغي").length,low=p.filter(x=>+x.qty<=+x.min).length;el.innerHTML=`<div class="stats"><div class="stat">👤 <b>${c.length}</b><span>عملاء</span></div><div class="stat">🔧 <b>${d.length}</b><span>أجهزة</span></div><div class="stat">🛠️ <b>${open}</b><span>أوامر مفتوحة</span></div><div class="stat">📦 <b>${low}</b><span>قطع منخفضة</span></div></div>`}
function monthReport(){let el=document.getElementById("monthlyReport");if(!el)return;let m=document.getElementById("reportMonth");if(!m.value)m.value=new Date().toISOString().slice(0,7);let ym=m.value,r=arr(K.r).filter(x=>x.closedAt?.slice(0,7)===ym||x.createdAt?.slice(0,7)===ym);let labor=r.reduce((a,x)=>a+(+x.labor||0),0),partsSell=r.reduce((a,x)=>a+(+x.partsTotal||0),0),partsCost=r.reduce((a,x)=>a+(+x.partsCost||0),0),revenue=labor+partsSell,profit=labor+partsSell-partsCost,paid=r.reduce((a,x)=>a+(+x.deposit||0),0),remain=r.reduce((a,x)=>a+Math.max(0,(+x.total||0)-(+x.deposit||0)),0);el.innerHTML=`<div class="stats"><div class="stat">🔨 <b>${labor.toFixed(2)}</b><span>مصنعية</span></div><div class="stat">🔧 <b>${partsSell.toFixed(2)}</b><span>قطع غيار محصلة</span></div><div class="stat">📦 <b>${partsCost.toFixed(2)}</b><span>تكلفة القطع</span></div><div class="stat">📈 <b>${profit.toFixed(2)}</b><span>المكسب</span></div><div class="stat">💰 <b>${revenue.toFixed(2)}</b><span>الإيراد</span></div><div class="stat">💵 <b>${paid.toFixed(2)}</b><span>العربون</span></div><div class="stat">🧾 <b>${remain.toFixed(2)}</b><span>المتبقي</span></div><div class="stat">🛠️ <b>${r.length}</b><span>أوامر الشهر</span></div></div>`}
function initCustomers(){let f=document.getElementById("customerForm");if(!f)return;fillCenters(cCenter);fillCenters(aCenter);function sync(){fillVillages(cVillage,cCenter.value);fillVillages(aVillage,aCenter.value)}cCenter.onchange=sync;aCenter.onchange=()=>fillVillages(aVillage,aCenter.value);f.onsubmit=e=>{e.preventDefault();let c={id:id(),name:cName.value.trim(),phone:cPhone.value.trim(),mainAddress:{center:cCenter.value,village:cVillage.value,address:cAddress.value.trim(),street:cStreet.value.trim()},extraAddress:{center:aCenter.value,village:aVillage.value,address:aAddress.value.trim(),street:aStreet.value.trim()},createdAt:new Date().toISOString()};let a=arr(K.c);a.push(c);put(K.c,a);location.href=`customer.html?id=${c.id}`};customerSearch.oninput=renderCustomers;renderCustomers()}
function renderCustomers(){let el=document.getElementById("customerList");if(!el)return;let q=(customerSearch?.value||"").toLowerCase(),a=arr(K.c).filter(c=>(c.name+" "+c.phone+" "+addressText(c.mainAddress)).toLowerCase().includes(q));el.innerHTML=a.length?a.map(c=>`<div class="item"><div class="item-head"><a href="customer.html?id=${c.id}"><b>👤 ${esc(c.name)}</b></a><span class="badge">🔧 ${arr(K.d).filter(d=>d.customerId===c.id).length} أجهزة • 🛠️ ${arr(K.r).filter(r=>r.customerId===c.id).length} أوامر</span></div><div>📞 ${esc(c.phone)}</div><div>📍 ${esc(addressText(c.mainAddress))}</div><a class="primary" href="customer.html?id=${c.id}">فتح 360°</a></div>`).join(""):'<div class="item">لا توجد نتائج.</div>'}
function customerProfile(){let el=document.getElementById("customerProfile");if(!el)return;let c=arr(K.c).find(x=>x.id===new URLSearchParams(location.search).get("id"));if(!c){el.innerHTML="<div class='item'>العميل غير موجود.</div>";return}let ds=arr(K.d).filter(d=>d.customerId===c.id),rs=arr(K.r).filter(r=>r.customerId===c.id);el.innerHTML=`<div class="profile"><div class="page-head"><h1>👤 ${esc(c.name)}</h1><div><a class="primary" href="devices.html?customer=${c.id}">➕ جهاز</a> <a class="primary" href="requests.html?customer=${c.id}">➕ أمر شغل</a></div></div><div class="profile-grid"><div class="kv"><b>📞 التليفون</b>${esc(c.phone)}</div><div class="kv"><b>📍 العنوان الأساسي</b>${esc(addressText(c.mainAddress))}</div><div class="kv"><b>📍 العنوان الإضافي</b>${c.extraAddress?.address?esc(addressText(c.extraAddress)):"—"}</div><div class="kv"><b>📊 الملخص</b>${ds.length} أجهزة • ${rs.length} أوامر</div></div></div><h2>🔧 الأجهزة</h2>${ds.length?ds.map(d=>`<div class="item"><a href="device.html?id=${d.id}"><b>${esc(d.type)} — ${esc(d.brand)}</b></a><div>${esc(d.category)} • ${esc(d.model||"بدون موديل")}</div><a class="secondary" href="requests.html?customer=${c.id}&device=${d.id}">🛠️ أمر شغل</a></div>`).join(""):"<div class='item'>لا توجد أجهزة.</div>"}<h2>🛠️ أوامر الشغل</h2>${rs.length?rs.map(r=>`<div class="item"><a href="request.html?id=${r.id}"><b>${esc(r.no)}</b></a> <span class="badge">${esc(r.status)}${r.closed?" 🔒":""}</span><div>${esc(deviceName(r.deviceId))} • الإجمالي ${(+r.total||0).toFixed(2)} ج</div></div>`).join(""):"<div class='item'>لا توجد أوامر.</div>"}`}
function initDevices(){let f=document.getElementById("deviceForm");if(!f)return;fillCustomer(dCustomer,new URLSearchParams(location.search).get("customer")||"");fillTypes(dType);fillBrands(dBrand);function syncAddr(){fillAddress(dAddress,dCustomer.value)}function syncCat(){fillCats(dCategory,dType.value)}dCustomer.onchange=syncAddr;dType.onchange=syncCat;dPhoto.onchange=previewImage;f.onsubmit=saveDevice;deviceSearch.oninput=renderDevices;syncAddr();renderDevices()}
function previewImage(e){let file=e.target.files[0],out=document.getElementById("photoPreview");if(!file)return;let r=new FileReader();r.onload=()=>out.innerHTML=`<img class="photo" src="${r.result}">`;r.readAsDataURL(file)}
function saveDevice(e){e.preventDefault();let file=dPhoto.files[0];let done=photo=>{let d={id:id(),customerId:dCustomer.value,addressKey:dAddress.value,type:dType.value,category:dCategory.value,brand:dBrand.value,model:dModel.value,desc:dDesc.value,photo:photo||"",createdAt:new Date().toISOString()};let a=arr(K.d);a.push(d);put(K.d,a);location.href=`device.html?id=${d.id}`};if(file){let r=new FileReader();r.onload=()=>done(r.result);r.readAsDataURL(file)}else done("")}
function renderDevices(){let el=document.getElementById("deviceList");if(!el)return;let q=(deviceSearch?.value||"").toLowerCase();let a=arr(K.d).filter(d=>(customerName(d.customerId)+" "+d.type+" "+d.brand).toLowerCase().includes(q));el.innerHTML=a.length?a.map(d=>`<div class="item"><div class="item-head"><a href="device.html?id=${d.id}"><b>🔧 ${esc(d.type)} — ${esc(d.brand)}</b></a><span class="badge">${esc(customerName(d.customerId))}</span></div><div>${esc(d.category)} • ${esc(d.model||"—")}</div><a class="primary" href="device.html?id=${d.id}">فتح 360°</a></div>`).join(""):'<div class="item">لا توجد أجهزة.</div>'}
function deviceProfile(){let el=document.getElementById("deviceProfile");if(!el)return;let d=arr(K.d).find(x=>x.id===new URLSearchParams(location.search).get("id"));if(!d){el.innerHTML="<div class='item'>الجهاز غير موجود.</div>";return}let rs=arr(K.r).filter(r=>r.deviceId===d.id);el.innerHTML=`<div class="profile"><div class="page-head"><h1>🔧 ${esc(d.type)} — ${esc(d.brand)}</h1><a class="primary" href="requests.html?customer=${d.customerId}&device=${d.id}">➕ أمر شغل</a></div><div class="profile-grid"><div class="kv"><b>👤 العميل</b><a href="customer.html?id=${d.customerId}">${esc(customerName(d.customerId))}</a></div><div class="kv"><b>📍 العنوان</b>${esc(addressText((arr(K.c).find(c=>c.id===d.customerId)||{}).mainAddress||{}))}</div><div class="kv"><b>النوع / التصنيف</b>${esc(d.type)} / ${esc(d.category)}</div><div class="kv"><b>الموديل</b>${esc(d.model)||"—"}</div></div>${d.photo?`<img class="photo" src="${d.photo}">`:""}<h2>🛠️ سجل أوامر الشغل</h2>${rs.length?rs.map(r=>`<div class="item"><a href="request.html?id=${r.id}"><b>${esc(r.no)}</b></a> <span class="badge">${esc(r.status)}</span><div>${esc(r.fault)}</div></div>`).join(""):"<div class='item'>لا يوجد سجل.</div>"}</div>`}
function initRequests(){let f=document.getElementById("requestForm");if(!f)return;let q=new URLSearchParams(location.search);fillCustomer(rCustomer,q.get("customer")||"");fillAddress(rAddress,rCustomer.value);fillDevice(rDevice,rCustomer.value,q.get("device")||"");rCustomer.onchange=()=>{fillAddress(rAddress,rCustomer.value);fillDevice(rDevice,rCustomer.value,"")};rLabor.oninput=calc; rDeposit.oninput=calc;rPart.innerHTML='<option value="">اختر قطعة</option>'+arr(K.p).map(p=>`<option value="${p.id}">${esc(p.name)} — ${p.use||0} ج — ${p.qty} متاح</option>`).join("");f.onsubmit=saveRequest;requestSearch.oninput=renderRequests;statusFilter.onchange=renderRequests;renderRequests();calc()}
function fillDevice(el,cid,selected=""){el.innerHTML='<option value="">اختر الجهاز</option>'+arr(K.d).filter(d=>d.customerId===cid).map(d=>`<option value="${d.id}" ${d.id===selected?"selected":""}>${esc(d.type)} — ${esc(d.brand)}</option>`).join("")}
let currentParts=[];
function addPartToOrder(){let pid=rPart.value,q=+rPartQty.value||0,p=arr(K.p).find(x=>x.id===pid);if(!p||q<1)return;if(q>+p.qty)return alert("الكمية غير متاحة في المخزن");currentParts.push({partId:pid,qty:q,sell:+p.use||0,cost:+p.buy||0});renderOrderParts();calc()}
function renderOrderParts(){let el=document.getElementById("orderParts");el.innerHTML=currentParts.map((x,i)=>{let p=arr(K.p).find(z=>z.id===x.partId);return `<div class="part-row"><span>${esc(p?.name)}</span><input type="number" min="1" value="${x.qty}" onchange="currentParts[${i}].qty=+this.value;calc();renderOrderParts()"><span>${(x.qty*x.sell).toFixed(2)} ج</span><button type="button" class="secondary" onclick="currentParts.splice(${i},1);renderOrderParts();calc()">🗑️</button></div>`}).join("")}
function calc(){let ps=currentParts.reduce((a,x)=>a+x.qty*x.sell,0),t=ps+(+rLabor.value||0),dep=+rDeposit.value||0;rPartsTotal.value=ps.toFixed(2);rTotal.value=t.toFixed(2);remainBox.classList.toggle("hidden",dep<=0);rRemain.value=Math.max(0,t-dep).toFixed(2)}
function saveRequest(e){e.preventDefault();let t=+rTotal.value||0,dep=+rDeposit.value||0;if(dep>t)return alert("العربون لا يمكن أن يتجاوز الإجمالي");let r={id:id(),no:"WO-"+new Date().getFullYear()+"-"+String(arr(K.r).length+1).padStart(4,"0"),customerId:rCustomer.value,deviceId:rDevice.value,addressKey:rAddress.value,priority:rPriority.value,visit:rVisit.value,status:rStatus.value,fault:rFault.value,work:rWork.value,labor:+rLabor.value||0,parts:currentParts,partsTotal:+rPartsTotal.value||0,partsCost:currentParts.reduce((a,x)=>a+x.qty*x.cost,0),total:t,deposit:dep,remain:Math.max(0,t-dep),closed:false,createdAt:new Date().toISOString()};let a=arr(K.r);a.push(r);put(K.r,a);location.href=`request.html?id=${r.id}`}
function renderRequests(){let el=document.getElementById("requestList");if(!el)return;let q=(requestSearch?.value||"").toLowerCase(),sf=statusFilter?.value||"";let a=arr(K.r).filter(r=>(r.no+" "+customerName(r.customerId)+" "+r.fault).toLowerCase().includes(q)&&(sf===""||r.status===sf));el.innerHTML=a.length?a.map(r=>`<div class="item"><div class="item-head"><a href="request.html?id=${r.id}"><b>🛠️ ${esc(r.no)}</b></a><span class="badge">${esc(r.status)}${r.closed?" 🔒":""}</span></div><div>👤 ${esc(customerName(r.customerId))} • 🔧 ${esc(deviceName(r.deviceId))}</div><div>💰 ${(+r.total||0).toFixed(2)} ج • 🧾 متبقي ${(+r.remain||0).toFixed(2)} ج</div></div>`).join(""):'<div class="item">لا توجد أوامر.</div>'}
function requestProfile(){let el=document.getElementById("requestProfile");if(!el)return;let r=arr(K.r).find(x=>x.id===new URLSearchParams(location.search).get("id"));if(!r){el.innerHTML="<div class='item'>الأمر غير موجود.</div>";return}let parts=r.parts.map(x=>{let p=arr(K.p).find(z=>z.id===x.partId);return `<div class="item">🔧 ${esc(p?.name)} × ${x.qty} = ${(x.qty*x.sell).toFixed(2)} ج</div>`}).join("");el.innerHTML=`<div class="profile"><div class="page-head"><h1>🛠️ ${esc(r.no)}</h1>${r.closed?"<span class='badge'>🔒 مغلق نهائيًا</span>":`<button class='primary' onclick="closeOrder('${r.id}')">🔒 إغلاق نهائي</button>`}</div><div class="profile-grid"><div class="kv"><b>👤 العميل</b><a href="customer.html?id=${r.customerId}">${esc(customerName(r.customerId))}</a></div><div class="kv"><b>🔧 الجهاز</b><a href="device.html?id=${r.deviceId}">${esc(deviceName(r.deviceId))}</a></div><div class="kv"><b>📍 العنوان</b>${esc(addressText((arr(K.c).find(c=>c.id===r.customerId)||{}).mainAddress||{}))}</div><div class="kv"><b>الحالة</b>${esc(r.status)}</div><div class="kv"><b>الأولوية</b>${esc(r.priority)}</div><div class="kv"><b>موعد الزيارة</b>${r.visit?esc(new Date(r.visit).toLocaleString("ar-EG")):"—"}</div></div><h2>📝 العطل</h2><div class="item">${esc(r.fault)}</div><h2>🔧 الأعمال</h2><div class="item">${esc(r.work)||"—"}</div><h2>💰 الحساب</h2><div class="calc-grid"><div class="kv">🔨 المصنعية <b>${r.labor.toFixed(2)} ج</b></div><div class="kv">🔧 قطع الغيار <b>${r.partsTotal.toFixed(2)} ج</b></div><div class="kv">💰 الإجمالي <b>${r.total.toFixed(2)} ج</b></div><div class="kv">💵 العربون <b>${r.deposit.toFixed(2)} ج</b></div>${r.deposit>0?`<div class="kv">🧾 المتبقي <b>${r.remain.toFixed(2)} ج</b></div>`:""}</div><h2>🔧 قطع الغيار</h2>${parts||"<div class='item'>لا توجد قطع.</div>"}</div>`}
function closeOrder(i){let a=arr(K.r),r=a.find(x=>x.id===i);if(!r||r.closed)return;if(r.status!=="مكتمل"){alert("لا يمكن الإغلاق النهائي إلا بعد جعل الأمر مكتمل.");return}if(!confirm("هل أنت متأكد؟ بعد الإغلاق النهائي لن يمكن تعديل أمر الشغل."))return;r.closed=true;r.closedAt=new Date().toISOString();put(K.r,a);location.reload()}
function initParts(){let f=document.getElementById("partForm");if(!f)return;fillPartCats(pCategory);pPhoto.onchange=e=>previewPart(e);f.onsubmit=savePart;partSearch.oninput=renderParts;renderParts()}
function fillPartCats(el,selected=""){el.innerHTML='<option value="">اختر التصنيف</option>'+settings().partCats.map(x=>`<option ${x===selected?"selected":""}>${esc(x)}</option>`).join("")}
function previewPart(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>partPhotoPreview.innerHTML=`<img class="photo" src="${r.result}">`;r.readAsDataURL(f)}
function savePart(e){e.preventDefault();let file=pPhoto.files[0],done=photo=>{let p={id:id(),name:pName.value,code:pCode.value,category:pCategory.value,location:pLocation.value,qty:+pQty.value||0,min:+pMin.value||0,buy:+pBuy.value||0,use:+pUse.value||0,photo:photo||"",createdAt:new Date().toISOString()};let a=arr(K.p);a.push(p);put(K.p,a);location.href=`part.html?id=${p.id}`};if(file){let r=new FileReader();r.onload=()=>done(r.result);r.readAsDataURL(file)}else done("")}
function renderParts(){let el=document.getElementById("partList");if(!el)return;let q=(partSearch?.value||"").toLowerCase();let a=arr(K.p).filter(p=>(p.name+" "+p.code+" "+p.location).toLowerCase().includes(q));el.innerHTML=a.length?a.map(p=>`<div class="item"><div class="item-head"><a href="part.html?id=${p.id}"><b>📦 ${esc(p.name)}</b></a><span class="badge">${p.qty} قطعة</span></div><div>${esc(p.category)} • 📍 ${esc(p.location)||"—"}</div><div>شراء ${p.buy} ج • استخدام ${p.use} ج</div></div>`).join(""):'<div class="item">لا توجد قطع.</div>'}
function partProfile(){let el=document.getElementById("partProfile");if(!el)return;let p=arr(K.p).find(x=>x.id===new URLSearchParams(location.search).get("id"));if(!p){el.innerHTML="<div class='item'>القطعة غير موجودة.</div>";return}el.innerHTML=`<div class="profile"><h1>📦 ${esc(p.name)}</h1><div class="profile-grid"><div class="kv"><b>الكود</b>${esc(p.code)||"—"}</div><div class="kv"><b>التصنيف</b>${esc(p.category)}</div><div class="kv"><b>المكان</b>📍 ${esc(p.location)||"—"}</div><div class="kv"><b>الكمية</b>${p.qty}</div><div class="kv"><b>الحد الأدنى</b>${p.min}</div><div class="kv"><b>سعر الشراء</b>${p.buy} ج</div><div class="kv"><b>سعر الاستخدام</b>${p.use} ج</div></div>${p.photo?`<img class="photo" src="${p.photo}">`:""}</div>`}
function settingsPage(){if(!document.getElementById("centerSettings"))return;let s=settings();centerSettings.innerHTML=s.centers.map(c=>`<div class="setting-row"><b>${esc(c)}</b><span><button class="secondary" onclick="renameCenter('${esc(c)}')">✏️</button> <button class="secondary" onclick="deleteCenter('${esc(c)}')">🗑️</button></span></div><div class="hint">قرى: ${(s.villages[c]||[]).join("، ")||"لا توجد"}</div>`).join("");typeSettings.innerHTML=Object.entries(s.types).map(([t,c])=>`<div class="setting-row"><b>${esc(t)}</b><span><button class="secondary" onclick="renameType('${esc(t)}')">✏️</button> <button class="secondary" onclick="deleteType('${esc(t)}')">🗑️</button></span></div><div class="hint">${c.join("، ")}</div>`).join("");brandSettings.innerHTML=s.brands.map(b=>`<div class="setting-row"><span>${esc(b)}</span><button class="secondary" onclick="deleteBrand('${esc(b)}')">🗑️</button></div>`).join("");partCategorySettings.innerHTML=s.partCats.map(b=>`<div class="setting-row"><span>${esc(b)}</span><button class="secondary" onclick="deletePartCategory('${esc(b)}')">🗑️</button></div>`).join("")}
function addCenter(){let s=settings(),x=newCenter.value.trim();if(!x||s.centers.includes(x))return;s.centers.push(x);s.villages[x]=[];put(K.s,s);settingsPage()} function renameCenter(x){let n=prompt("الاسم الجديد",x);if(!n||n===x)return;let s=settings(),i=s.centers.indexOf(x);s.centers[i]=n;s.villages[n]=s.villages[x]||[];delete s.villages[x];put(K.s,s);settingsPage()} function deleteCenter(x){if(!confirm("حذف المركز؟"))return;let s=settings();s.centers=s.centers.filter(a=>a!==x);delete s.villages[x];put(K.s,s);settingsPage()}
function addType(){let s=settings(),x=newType.value.trim();if(!x||s.types[x])return;s.types[x]=[];put(K.s,s);settingsPage()}function renameType(x){let n=prompt("الاسم الجديد",x);if(!n||n===x)return;let s=settings();s.types[n]=s.types[x]||[];delete s.types[x];put(K.s,s);settingsPage()}function deleteType(x){if(!confirm("حذف النوع؟"))return;let s=settings();delete s.types[x];put(K.s,s);settingsPage()}function addBrand(){let s=settings(),x=newBrand.value.trim();if(!x||s.brands.includes(x))return;s.brands.push(x);put(K.s,s);settingsPage()}function deleteBrand(x){let s=settings();s.brands=s.brands.filter(a=>a!==x);put(K.s,s);settingsPage()}function addPartCategory(){let s=settings(),x=newPartCategory.value.trim();if(!x||s.partCats.includes(x))return;s.partCats.push(x);put(K.s,s);settingsPage()}function deletePartCategory(x){let s=settings();s.partCats=s.partCats.filter(a=>a!==x);put(K.s,s);settingsPage()}
document.addEventListener("DOMContentLoaded",()=>{settings();renderDash();monthReport();document.getElementById("reportMonth")?.addEventListener("change",monthReport);initCustomers();customerProfile();initDevices();deviceProfile();initRequests();requestProfile();initParts();partProfile();settingsPage()})
