const K={customers:'wm5_customers',devices:'wm5_devices',requests:'wm5_requests',parts:'wm5_parts',audit:'wm5_audit'};
const OLD={customers:'wm4_customers',devices:'wm4_devices',requests:'wm4_requests',parts:'wm4_parts',audit:'wm4_audit'};
const qs=new URLSearchParams(location.search),$=id=>document.getElementById(id);
const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'[]')}catch{return[]}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function migrate(){Object.keys(K).forEach(k=>{if(!localStorage.getItem(K[k])&&localStorage.getItem(OLD[k]))localStorage.setItem(K[k],localStorage.getItem(OLD[k]))})}
migrate();
const C=()=>read(K.customers),D=()=>read(K.devices),R=()=>read(K.requests),P=()=>read(K.parts),A=()=>read(K.audit);
const find=(a,i)=>a.find(x=>x.id===i), cname=i=>find(C(),i)?.name||'غير معروف';
const dname=i=>{let d=find(D(),i);return d?`${d.type}${d.subtype?' - '+d.subtype:''} - ${d.brand}${d.model?' - '+d.model:''}`:'غير معروف'};
function log(action,entity,entityId,details=''){let a=A();a.unshift({id:uid(),at:new Date().toISOString(),action,entity,entityId,details});write(K.audit,a.slice(0,200))}
function fmt(v){return v?new Date(v).toLocaleString('ar-EG'):'—'}
function fileToData(input,cb){let f=input?.files?.[0];if(!f){cb('');return}let r=new FileReader();r.onload=()=>cb(r.result);r.readAsDataURL(f)}
function addresses(c){if(!c)return[];if(Array.isArray(c.addresses)&&c.addresses.length)return c.addresses;return[{id:'main',label:'العنوان الأساسي',area:c.area||'',village:c.village||'',address:c.address||''}]}
function addrText(c,a){return a?`${a.area||c?.area||''}${a.village?' - '+a.village:''}${a.address?' - '+a.address:''}`:'—'}
function fillCustomers(el,sel=''){if(!el)return;el.innerHTML='<option value="">اختر العميل</option>'+C().map(c=>`<option value="${c.id}" ${c.id===sel?'selected':''}>${esc(c.name)} — ${esc(c.phone)}</option>`).join('')}
function fillAddresses(el,cid,sel=''){if(!el)return;let c=find(C(),cid);el.innerHTML='<option value="">اختر العنوان</option>'+addresses(c).map(a=>`<option value="${a.id}" ${a.id===sel?'selected':''}>${esc(a.label||'عنوان')} — ${esc(addrText(c,a))}</option>`).join('')}
function fillDevices(el,cid,sel=''){if(!el)return;el.innerHTML='<option value="">اختر الجهاز</option>'+D().filter(d=>d.customerId===cid).map(d=>`<option value="${d.id}" ${d.id===sel?'selected':''}>${esc(dname(d.id))}</option>`).join('')}
const MATAY_VILLAGES=['مطاي البلد','أبجاج الحطب','أبوان','أبو حسيبة','أبو شحاتة','أبو عزيز','أدقاق المسك','الأطلات','الروضة','الشيخ حسن','بردنوها','حلوة','بني عمار','سيلة الشرقية','سيلة الغربية','عزبة هوارة','كفر الكوادي','كوم مطاي','كفور الصولية','كوم والي','منبال','منشأة منبال','منشأة لطف الله','نزلة أولاد الشيخ','جوادة','مرزوق','الهمة'];
const BRANDS=['توشيبا','شارب','سامسونج','إل جي','بيكو','فريش','تورنيدو','زانوسي','أريستون','إنديست','وايت بوينت','هوفر','بوش','سيمنس','ويرلبول','كريازي','إيديال','يونيون إير','وايت ويل','ألاسكا','أوليمبيك إليكتريك','يونيفرسال','بريما','نيكاي','ميديا','جري','كاريير','يونيون إير','يورك','جنرال','فريجيدير','كولدير','لا جيرمانيا','أخرى'];
const DEVICE_TYPES={
 'ثلاجة':['عادية','نوفروست','ديجيتال','إنفرتر','أخرى'],
 'فريزر':['أفقي','رأسي','إنفرتر','أخرى'],
 'غسالة':['هاف أوتوماتيك','فوق أوتوماتيك','أمامي أوتوماتيك','أخرى'],
 'تكييف':['سبليت عادي','سبليت إنفرتر','شباك','أخرى'],
 'سخان مياه':['كهرباء','غاز','شمسي','أخرى'],
 'سخان غاز':['سخان غاز','أخرى'],
 'كولدير':['كولدير مياه','أخرى'],
 'بوتاجاز':['غاز طبيعي','غاز أسطوانة','كهرباء','أخرى'],
 'أخرى':['أخرى']
};
function fillBrand(el,sel=''){if(!el)return;el.innerHTML='<option value="">اختر الماركة</option>'+BRANDS.map(b=>`<option ${b===sel?'selected':''}>${esc(b)}</option>`).join('')}
function fillDeviceTypes(el,sel=''){if(!el)return;el.innerHTML='<option value="">اختر نوع الجهاز</option>'+Object.keys(DEVICE_TYPES).map(t=>`<option ${t===sel?'selected':''}>${esc(t)}</option>`).join('')}
function fillSubtypes(el,type,sel=''){if(!el)return;let arr=DEVICE_TYPES[type]||[];el.innerHTML='<option value="">اختر التصنيف</option>'+arr.map(x=>`<option ${x===sel?'selected':''}>${esc(x)}</option>`).join('');el.disabled=!arr.length}
function stats(){let s=$('stats');if(s)s.innerHTML=[['العملاء',C().length],['الأجهزة',D().length],['طلبات الصيانة',R().length],['قطع الغيار',P().length]].map(x=>`<div class="stat"><strong>${x[1]}</strong><span>${x[0]}</span></div>`).join('');let al=$('alerts');if(al){let now=new Date(),end=new Date(now.getTime()+30*864e5),w=R().filter(r=>r.warrantyEnd&&new Date(r.warrantyEnd)>=now&&new Date(r.warrantyEnd)<=end),low=P().filter(p=>+p.qty<=+p.min),out=P().filter(p=>+p.qty===0);al.innerHTML=(w.length?`<div class="item warning">⚠️ ${w.length} ضمانات تقترب من الانتهاء خلال 30 يومًا.</div>`:'')+(low.length?`<div class="item warning">📦 ${low.length} قطع عند الحد الأدنى أو أقل.</div>`:'')+(out.length?`<div class="item danger">⛔ ${out.length} قطع نافدة.</div>`:'')||'<div class="empty">لا توجد تنبيهات.</div>'}}
function initCustomer(){if(!$('customerForm'))return;let edit=qs.get('id'),c=edit?find(C(),edit):null;
 let vill=$('village');vill.innerHTML='<option value="">اختر القرية</option>'+MATAY_VILLAGES.map(v=>`<option>${esc(v)}</option>`).join('');
 if(c){$('customerId').value=c.id;$('customerName').value=c.name;$('customerPhone').value=c.phone;$('area').value=c.area||'';$('village').value=c.village||'';$('address').value=c.address||'';$('workTime').value=c.workTime||'';$('extraAddresses').innerHTML=addresses(c).slice(1).map(addressRow).join('');$('cancelCustomer').classList.remove('hidden')}
 $('area').onchange=()=>{$('village').disabled=$('area').value!=='مطاي';if($('area').value!=='مطاي')$('village').value=''};$('area').dispatchEvent(new Event('change'));
 $('addAddress').onclick=()=>{$('extraAddresses').insertAdjacentHTML('beforeend',addressRow());bindAddressRemove()};
 function bindAddressRemove(){document.querySelectorAll('.removeAddress').forEach(b=>b.onclick=()=>b.closest('.addressrow').remove())}bindAddressRemove();
 $('customerForm').onsubmit=e=>{e.preventDefault();let arr=C(),i=$('customerId').value,main={id:'main',label:'العنوان الأساسي',area:$('area').value,village:$('area').value==='مطاي'?$('village').value:'',address:$('address').value.trim()},extra=[...document.querySelectorAll('.addressrow')].map(r=>({id:r.dataset.id||uid(),label:r.querySelector('.alabel').value.trim()||'عنوان إضافي',area:r.querySelector('.aarea').value,village:r.querySelector('.aarea').value==='مطاي'?r.querySelector('.avillage').value.trim():'',address:r.querySelector('.aaddress').value.trim()})).filter(a=>a.address),obj={id:i||uid(),name:$('customerName').value.trim(),phone:$('customerPhone').value.trim(),area:main.area,village:main.village,address:main.address,workTime:$('workTime').value,addresses:[main,...extra],createdAt:i?(find(arr,i)?.createdAt||new Date().toISOString()):new Date().toISOString()};if(!obj.name||!obj.phone||!obj.area||!obj.address){alert('أكمل البيانات الأساسية للعميل');return}if(i)arr[arr.findIndex(x=>x.id===i)]=obj;else arr.push(obj);write(K.customers,arr);log(i?'تعديل عميل':'إضافة عميل','العملاء',obj.id,obj.name);location.href=`customer.html?id=${obj.id}`};
 $('cancelCustomer').onclick=()=>location.href='customers.html';$('customerSearch').oninput=renderCustomers;renderCustomers()}
function addressRow(a={}){return `<div class="addressrow sectionbox" data-id="${a.id||''}"><div class="grid2"><label>اسم العنوان<input class="alabel" value="${esc(a.label||'')}" placeholder="المنزل / العمل"></label><label>المنطقة<select class="aarea"><option ${a.area==='مطاي'?'selected':''}>مطاي</option><option ${a.area==='بني مزار'?'selected':''}>بني مزار</option></select></label></div><label>القرية<input class="avillage" value="${esc(a.village||'')}" placeholder="اكتب القرية"></label><label>العنوان التفصيلي<input class="aaddress" value="${esc(a.address||'')}"></label><button type="button" class="secondary removeAddress">حذف العنوان</button></div>`}
function renderCustomers(){let l=$('customerList');if(!l)return;let q=($('customerSearch')?.value||'').trim().toLowerCase();let arr=C().filter(c=>(`${c.name} ${c.phone} ${c.area} ${c.village} ${c.address}`).toLowerCase().includes(q));l.innerHTML=arr.map(c=>{let ds=D().filter(d=>d.customerId===c.id).length,rs=R().filter(r=>r.customerId===c.id).length;return `<div class="item"><div class="item-head"><a href="customer.html?id=${c.id}"><strong>${esc(c.name)}</strong></a><span class="badge">${ds} أجهزة • ${rs} طلبات</span></div><div>📞 ${esc(c.phone)}</div><div>📍 ${esc(addrText(c,addresses(c)[0]))}</div><div class="actions"><a class="btn" href="customer.html?id=${c.id}">فتح ملف 360°</a><a class="btn secondary" href="customers.html?id=${c.id}">تعديل</a></div></div>`}).join('')||'<div class="empty">لا يوجد عملاء مطابقون.</div>'}
function customerProfile(){let b=$('customerProfile');if(!b)return;let c=find(C(),qs.get('id'));if(!c){b.innerHTML='<div class="empty">العميل غير موجود.</div>';return}let ds=D().filter(d=>d.customerId===c.id),rs=R().filter(r=>r.customerId===c.id);b.innerHTML=`<div class="profile"><div class="head"><h1>${esc(c.name)}</h1><div class="actions"><a class="btn secondary" href="customers.html?id=${c.id}">تعديل البيانات</a><a class="btn" href="requests.html?customer=${c.id}">+ أمر شغل</a><a class="btn" href="devices.html?customer=${c.id}">+ جهاز</a></div></div><div class="profilegrid"><div class="kv"><b>التليفون</b>${esc(c.phone)}</div><div class="kv"><b>المنطقة</b>${esc(c.area)}</div><div class="kv"><b>القرية</b>${esc(c.village)||'—'}</div><div class="kv"><b>العنوان</b>${esc(c.address)}</div><div class="kv"><b>مواعيد العمل</b>${esc(c.workTime)||'—'}</div><div class="kv"><b>الأجهزة</b>${ds.length}</div><div class="kv"><b>طلبات الصيانة</b>${rs.length}</div></div></div><h2>عناوين العميل</h2>${addresses(c).map(a=>`<div class="item"><strong>${esc(a.label)}</strong><br>${esc(addrText(c,a))}</div>`).join('')}<h2>الأجهزة</h2>${ds.map(d=>`<div class="item"><div class="item-head"><a href="device.html?id=${d.id}"><strong>${esc(dname(d.id))}</strong></a><span class="badge">${esc(findAddress(c,d.addressId)?.label||'العنوان الأساسي')}</span></div><div>${esc(addrText(c,findAddress(c,d.addressId)))}</div><div>${esc(d.description)||'بدون وصف'}</div><div class="actions"><a class="btn" href="device.html?id=${d.id}">ملف الجهاز 360°</a><a class="btn secondary" href="requests.html?customer=${c.id}&device=${d.id}">+ طلب صيانة</a></div></div>`).join('')||'<div class="empty">لا توجد أجهزة. استخدم + جهاز لإضافة أول جهاز.</div>'}<h2>أوامر الشغل وطلبات الصيانة</h2>${rs.map(r=>`<div class="item"><div class="item-head"><a href="request.html?id=${r.id}"><strong>${esc(r.requestNo)}</strong></a><span class="badge">${esc(r.status)}</span></div><div>🔧 ${esc(dname(r.deviceId))}</div><div>${esc(r.fault)}</div><div>الإجمالي: ${money(r.total)} — المدفوع: ${money(r.paid)} — المتبقي: ${money(Math.max(0,r.total-r.paid))}</div><div class="actions"><a class="btn" href="request.html?id=${r.id}">فتح أمر الشغل 360°</a><a class="btn secondary" href="requests.html?id=${r.id}">تعديل</a></div></div>`).join('')||'<div class="empty">لا توجد طلبات.</div>'}`}
function findAddress(c,id){return addresses(c).find(a=>a.id===id)||addresses(c)[0]}
function money(n){return `${Number(n||0).toFixed(2)} جنيه`}
function initDevice(){if(!$('deviceForm'))return;let edit=qs.get('id'),old=edit?find(D(),edit):null,cid=old?.customerId||qs.get('customer')||'';fillCustomers($('deviceCustomer'),cid);fillDeviceTypes($('deviceType'),old?.type||'');fillBrand($('deviceBrand'),old?.brand||'');fillSubtypes($('deviceSubtype'),old?.type||'',old?.subtype||'');
 function sync(){fillAddresses($('deviceAddress'),$('deviceCustomer').value,old?.addressId||'');} $('deviceCustomer').onchange=()=>{old=null;sync()};$('deviceType').onchange=()=>fillSubtypes($('deviceSubtype'),$('deviceType').value);sync();
 if(old){$('deviceId').value=old.id;$('deviceModel').value=old.model||'';$('deviceDescription').value=old.description||'';$('deviceCondition').value=old.condition||'';$('deviceNotes').value=old.notes||'';$('cancelDevice').classList.remove('hidden');if(old.photo)$('photoPreview').innerHTML=`<img class="thumb" src="${old.photo}">`}
 $('deviceForm').onsubmit=e=>{e.preventDefault();let arr=D(),i=$('deviceId').value,o=i?find(arr,i):null;fileToData($('devicePhoto'),photo=>{let d={id:i||uid(),customerId:$('deviceCustomer').value,addressId:$('deviceAddress').value,type:$('deviceType').value,subtype:$('deviceSubtype').value,brand:$('deviceBrand').value,model:$('deviceModel').value.trim(),description:$('deviceDescription').value.trim(),condition:$('deviceCondition').value,notes:$('deviceNotes').value.trim(),photo:photo||o?.photo||'',createdAt:o?.createdAt||new Date().toISOString()};if(!d.customerId||!d.addressId||!d.type||!d.subtype||!d.brand){alert('اختر العميل والعنوان ونوع الجهاز وتصنيفه والماركة');return}if(i)arr[arr.findIndex(x=>x.id===i)]=d;else arr.push(d);write(K.devices,arr);log(i?'تعديل جهاز':'إضافة جهاز','الأجهزة',d.id,dname(d.id));location.href=`device.html?id=${d.id}`})};$('deviceSearch').oninput=renderDevices;$('deviceFilter').onchange=renderDevices;$('cancelDevice').onclick=()=>location.href='devices.html';renderDevices()}
function renderDevices(){let l=$('deviceList');if(!l)return;if($('deviceFilter').options.length<=1){let cur=$('deviceFilter').value;fillCustomers($('deviceFilter'));$('deviceFilter').insertAdjacentHTML('afterbegin','<option value="">كل العملاء</option>');$('deviceFilter').value=cur||qs.get('customer')||''}let q=($('deviceSearch')?.value||'').toLowerCase(),cid=$('deviceFilter')?.value||qs.get('customer')||'';let arr=D().filter(d=>(`${dname(d.id)} ${cname(d.customerId)}`).toLowerCase().includes(q)&&(cid===''||d.customerId===cid));l.innerHTML=arr.map(d=>`<div class="item"><div class="item-head"><a href="device.html?id=${d.id}"><strong>${esc(dname(d.id))}</strong></a><span class="badge">${esc(cname(d.customerId))}</span></div><div>${esc(addrText(find(C(),d.customerId),findAddress(find(C(),d.customerId),d.addressId)))}</div><div>${esc(d.description)||'بدون وصف'}</div><div class="actions"><a class="btn" href="device.html?id=${d.id}">فتح ملف 360°</a><a class="btn secondary" href="devices.html?id=${d.id}">تعديل</a></div></div>`).join('')||'<div class="empty">لا توجد أجهزة مطابقة.</div>'}
function deviceProfile(){let b=$('deviceProfile');if(!b)return;let d=find(D(),qs.get('id'));if(!d){b.innerHTML='<div class="empty">الجهاز غير موجود.</div>';return}let c=find(C(),d.customerId),rs=R().filter(r=>r.deviceId===d.id);b.innerHTML=`<div class="profile"><div class="head"><h1>${esc(dname(d.id))}</h1><div class="actions"><a class="btn secondary" href="devices.html?id=${d.id}">تعديل</a><a class="btn" href="requests.html?customer=${c?.id}&device=${d.id}">+ أمر شغل</a></div></div>${d.photo?`<img class="thumb big" src="${d.photo}">`:''}<div class="profilegrid"><div class="kv"><b>العميل</b><a href="customer.html?id=${c?.id}">${esc(c?.name)}</a></div><div class="kv"><b>التليفون</b>${esc(c?.phone)}</div><div class="kv"><b>العنوان</b>${esc(addrText(c,findAddress(c,d.addressId)))}</div><div class="kv"><b>النوع</b>${esc(d.type)}</div><div class="kv"><b>التصنيف</b>${esc(d.subtype)}</div><div class="kv"><b>الماركة</b>${esc(d.brand)}</div><div class="kv"><b>الموديل</b>${esc(d.model)||'—'}</div><div class="kv"><b>الحالة</b>${esc(d.condition)||'—'}</div></div><h3>وصف الجهاز</h3><div class="item">${esc(d.description)||'—'}</div><h2>سجل أوامر الشغل</h2>${rs.map(r=>`<div class="item"><div class="item-head"><a href="request.html?id=${r.id}"><strong>${esc(r.requestNo)}</strong></a><span class="badge">${esc(r.status)}</span></div><div>${esc(r.fault)}</div><div>الضمان حتى: ${r.warrantyEnd||'—'}</div><a class="btn" href="request.html?id=${r.id}">فتح أمر الشغل</a></div>`).join('')||'<div class="empty">لا يوجد سجل صيانة.</div>'}</div>`}
function partRow(x={}){let opts=P().map(p=>`<option value="${p.id}" ${p.id===x.partId?'selected':''}>${esc(p.name)} — المتاح ${p.qty}</option>`).join('');return `<div class="partrow sectionbox"><div class="grid2"><label>قطعة الغيار<select class="rpart">${opts}</select></label><label>الكمية<input class="rqty" type="number" min="1" step="1" value="${x.qty||1}"></label></div><button type="button" class="secondary removePart">حذف</button></div>`}
function initRequest(){if(!$('requestForm'))return;let edit=qs.get('id'),old=edit?find(R(),edit):null,cid=old?.customerId||qs.get('customer')||'',did=old?.deviceId||qs.get('device')||'';fillCustomers($('requestCustomer'),cid);fillDevices($('requestDevice'),cid,did);fillAddresses($('requestAddress'),cid,old?.addressId||'');$('requestCustomer').onchange=()=>{fillDevices($('requestDevice'),$('requestCustomer').value);fillAddresses($('requestAddress'),$('requestCustomer').value)};$('requestDevice').onchange=()=>{let d=find(D(),$('requestDevice').value);if(d)fillAddresses($('requestAddress'),d.customerId,d.addressId)};
 if(old){$('requestId').value=old.id;$('fault').value=old.fault;$('priority').value=old.priority;$('visitDate').value=old.visitDate||'';$('status').value=old.status;$('inspection').value=old.inspection||'';$('visitFee').value=old.visitFee||0;$('repairTotal').value=old.repairTotal||0;$('paid').value=old.paid||0;$('warrantyEnd').value=old.warrantyEnd||'';$('legalInvoice').checked=!!old.legalInvoice;$('requestParts').innerHTML=(old.parts||[]).map(partRow).join('');$('cancelRequest').classList.remove('hidden')}else{$('requestParts').innerHTML='';if(did)$('requestDevice').dispatchEvent(new Event('change'))}
 $('addRequestPart').onclick=()=>{if(!P().length){alert('أضف قطع الغيار للمخزن أولًا.');return}$('requestParts').insertAdjacentHTML('beforeend',partRow());bindPartRemove()};function bindPartRemove(){document.querySelectorAll('.removePart').forEach(b=>b.onclick=()=>b.closest('.partrow').remove())}bindPartRemove();
 $('requestForm').onsubmit=e=>{e.preventDefault();let arr=R(),i=$('requestId').value,o=i?find(arr,i):null,parts=[...document.querySelectorAll('.partrow')].map(r=>({partId:r.querySelector('.rpart').value,qty:+r.querySelector('.rqty').value||0})).filter(x=>x.partId&&x.qty>0);let d=find(D(),$('requestDevice').value),obj={id:i||uid(),requestNo:o?.requestNo||`WO-${new Date().getFullYear()}-${String(arr.length+1).padStart(4,'0')}`,customerId:$('requestCustomer').value,deviceId:$('requestDevice').value,addressId:$('requestAddress').value,fault:$('fault').value.trim(),priority:$('priority').value,visitDate:$('visitDate').value,status:$('status').value,inspection:$('inspection').value.trim(),visitFee:+$('visitFee').value||0,repairTotal:+$('repairTotal').value||0,paid:+$('paid').value||0,warrantyEnd:$('warrantyEnd').value,legalInvoice:$('legalInvoice').checked,parts,createdAt:o?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(!obj.customerId||!obj.deviceId||!obj.addressId||!obj.fault){alert('أكمل العميل والجهاز والعنوان ووصف العطل');return}if(obj.paid>obj.visitFee+obj.repairTotal){alert('المدفوع لا يمكن أن يتجاوز الإجمالي');return}
 let oldParts=o?.parts||[];if(!stockDelta(oldParts,parts))return;if(i)arr[arr.findIndex(x=>x.id===i)]=obj;else arr.push(obj);write(K.requests,arr);log(i?'تعديل أمر شغل':'إنشاء أمر شغل','طلبات الصيانة',obj.id,obj.requestNo);location.href=`request.html?id=${obj.id}`};$('cancelRequest').onclick=()=>location.href='requests.html';$('requestSearch').oninput=renderRequests;$('statusFilter').onchange=renderRequests;$('priorityFilter').onchange=renderRequests;renderRequests()}
function stockDelta(oldParts,newParts){let oldMap={},newMap={};oldParts.forEach(x=>oldMap[x.partId]=(oldMap[x.partId]||0)+x.qty);newParts.forEach(x=>newMap[x.partId]=(newMap[x.partId]||0)+x.qty);let ps=P();for(let p of ps){let delta=(newMap[p.id]||0)-(oldMap[p.id]||0);if(delta>0&&+p.qty<delta){alert(`الكمية غير كافية من: ${p.name}`);return false}}let now=new Date().toISOString();ps.forEach(p=>{let delta=(newMap[p.id]||0)-(oldMap[p.id]||0);if(!delta)return;p.qty=+p.qty-delta;p.moves=p.moves||[];p.moves.unshift({id:uid(),type:delta>0?'out':'in',qty:Math.abs(delta),at:now,reason:delta>0?'استخدام في أمر شغل':'إرجاع/تعديل أمر شغل',requestId:qs.get('id')||null})});write(K.parts,ps);return true}
function renderRequests(){let l=$('requestList');if(!l)return;let q=($('requestSearch')?.value||'').toLowerCase(),sf=$('statusFilter')?.value||'',pf=$('priorityFilter')?.value||'';let arr=R().filter(r=>(`${r.requestNo} ${cname(r.customerId)} ${r.fault}`).toLowerCase().includes(q)&&(sf===''||r.status===sf)&&(pf===''||r.priority===pf));l.innerHTML=arr.map(r=>`<div class="item"><div class="item-head"><a href="request.html?id=${r.id}"><strong>${esc(r.requestNo)}</strong></a><span class="badge">${esc(r.status)}</span></div><div>👤 ${esc(cname(r.customerId))} — 🔧 ${esc(dname(r.deviceId))}</div><div>${esc(r.fault)}</div><div>الإجمالي: ${money(r.visitFee+r.repairTotal)} — المدفوع: ${money(r.paid)} — المتبقي: ${money(Math.max(0,r.visitFee+r.repairTotal-r.paid))}</div><div>الضمان: ${r.warrantyEnd||'—'}</div></div>`).join('')||'<div class="empty">لا توجد طلبات مطابقة.</div>'}
function requestProfile(){let b=$('requestProfile');if(!b)return;let r=find(R(),qs.get('id'));if(!r){b.innerHTML='<div class="empty">أمر الشغل غير موجود.</div>';return}let c=find(C(),r.customerId),d=find(D(),r.deviceId),gross=r.visitFee+r.repairTotal,remain=Math.max(0,gross-r.paid),parts=r.parts||[];b.innerHTML=`<div class="profile"><div class="head"><h1>${esc(r.requestNo)}</h1><div class="actions"><a class="btn secondary" href="requests.html?id=${r.id}">تعديل أمر الشغل</a><a class="btn" href="customer.html?id=${c?.id}">ملف العميل</a><a class="btn" href="device.html?id=${d?.id}">ملف الجهاز</a></div></div><div class="profilegrid"><div class="kv"><b>العميل</b><a href="customer.html?id=${c?.id}">${esc(c?.name)}</a></div><div class="kv"><b>التليفون</b>${esc(c?.phone)}</div><div class="kv"><b>الجهاز</b><a href="device.html?id=${d?.id}">${esc(dname(r.deviceId))}</a></div><div class="kv"><b>العنوان</b>${esc(addrText(c,findAddress(c,r.addressId)))}</div><div class="kv"><b>الحالة</b>${esc(r.status)}</div><div class="kv"><b>الأولوية</b>${esc(r.priority)}</div><div class="kv"><b>موعد الزيارة</b>${fmt(r.visitDate)}</div><div class="kv"><b>الإجمالي</b>${money(gross)}</div><div class="kv"><b>المدفوع</b>${money(r.paid)}</div><div class="kv"><b>المتبقي</b>${money(remain)}</div><div class="kv"><b>نهاية الضمان</b>${r.warrantyEnd||'—'}</div><div class="kv"><b>الفاتورة القانونية</b>${r.legalInvoice?'صادرة':'لم تصدر'}</div></div><h2>وصف العطل</h2><div class="item">${esc(r.fault)}</div><h2>الكشف والأعمال المنفذة</h2><div class="item">${esc(r.inspection)||'—'}</div><h2>قطع الغيار المستخدمة</h2>${parts.map(x=>{let p=find(P(),x.partId);return `<div class="item">${esc(p?.name||'قطعة محذوفة')} × ${x.qty} — ${money((p?.use||0)*x.qty)}</div>`}).join('')||'<div class="empty">لا توجد قطع غيار مسجلة.</div>'}<div class="notice">التقدير أو الكشف المبدئي ليس فاتورة قانونية. الفاتورة القانونية النهائية تكون بعد اكتمال أمر الشغل وفق الإجراء المعتمد.</div></div>`}
function initPart(){if(!$('partForm'))return;let edit=qs.get('id'),old=edit?find(P(),edit):null;if(old){$('partId').value=old.id;$('partName').value=old.name;$('partCode').value=old.code||'';$('partCategory').value=old.category||'';$('partQty').value=old.qty;$('partMin').value=old.min||0;$('partBuy').value=old.buy||0;$('partUse').value=old.use||0;$('cancelPart').classList.remove('hidden');if(old.photo)$('partPhotoPreview').innerHTML=`<img class="thumb" src="${old.photo}">`}
 $('partForm').onsubmit=e=>{e.preventDefault();let arr=P(),i=$('partId').value,o=i?find(arr,i):null;fileToData($('partPhoto'),photo=>{let p={id:i||uid(),name:$('partName').value.trim(),code:$('partCode').value.trim(),category:$('partCategory').value.trim(),qty:+$('partQty').value||0,min:+$('partMin').value||0,buy:+$('partBuy').value||0,use:+$('partUse').value||0,photo:photo||o?.photo||'',moves:o?.moves||[],createdAt:o?.createdAt||new Date().toISOString()};if(!p.name){alert('اكتب اسم القطعة');return}if(i)arr[arr.findIndex(x=>x.id===i)]=p;else arr.push(p);write(K.parts,arr);log(i?'تعديل قطعة':'إضافة قطعة','المخزن',p.id,p.name);location.href=`part.html?id=${p.id}`})};$('partSearch').oninput=renderParts;$('stockFilter').onchange=renderParts;$('cancelPart').onclick=()=>location.href='inventory.html';renderParts()}
function renderParts(){let l=$('partList');if(!l)return;let q=($('partSearch')?.value||'').toLowerCase(),f=$('stockFilter')?.value||'';let arr=P().filter(p=>(`${p.name} ${p.code||''} ${p.category||''}`).toLowerCase().includes(q)&&(f===''||(f==='low'&&+p.qty<=+p.min)||(f==='out'&&+p.qty===0)));l.innerHTML=arr.map(p=>`<div class="item ${+p.qty<=+p.min?'low':''}"><div class="item-head"><a href="part.html?id=${p.id}"><strong>${esc(p.name)}</strong></a><span class="badge">${p.qty} قطعة</span></div><div>الكود: ${esc(p.code)||'—'} • التصنيف: ${esc(p.category)||'—'}</div><div>شراء: ${money(p.buy)} • استخدام: ${money(p.use)}</div><a class="btn" href="part.html?id=${p.id}">فتح ملف 360°</a></div>`).join('')||'<div class="empty">لا توجد قطع مطابقة.</div>'}
function partProfile(){let b=$('partProfile');if(!b)return;let p=find(P(),qs.get('id'));if(!p){b.innerHTML='<div class="empty">قطعة الغيار غير موجودة.</div>';return}let moves=p.moves||[];b.innerHTML=`<div class="profile"><div class="head"><h1>${esc(p.name)}</h1><a class="btn secondary" href="inventory.html?id=${p.id}">تعديل</a></div><div class="profilegrid"><div class="kv"><b>الكود</b>${esc(p.code)||'—'}</div><div class="kv"><b>التصنيف</b>${esc(p.category)||'—'}</div><div class="kv"><b>الكمية</b>${p.qty}</div><div class="kv"><b>الحد الأدنى</b>${p.min}</div><div class="kv"><b>سعر الشراء</b>${money(p.buy)}</div><div class="kv"><b>سعر الاستخدام</b>${money(p.use)}</div></div>${p.photo?`<img class="thumb big" src="${p.photo}">`:''}<h2>حركات المخزون</h2>${moves.map(m=>`<div class="item">${m.type==='in'?'دخول':'خروج'} — ${m.qty} — ${fmt(m.at)}<br>${esc(m.reason||'')}${m.requestId?' — أمر الشغل: '+esc(find(R(),m.requestId)?.requestNo||''):''}</div>`).join('')||'<div class="empty">لا توجد حركات.</div>'}</div>`;let p2=p;}
function bindMovement(){let b=$('addMove');if(!b)return;b.onclick=()=>{let arr=P(),p=find(arr,qs.get('id')),qty=+$('moveQty').value||0,type=$('moveType').value;if(!p||qty<1)return;if(type==='out'&&p.qty<qty){alert('الكمية الحالية لا تكفي.');return}p.qty+=type==='in'?qty:-qty;p.moves=p.moves||[];p.moves.unshift({id:uid(),type,qty,at:new Date().toISOString(),reason:$('moveReason').value.trim(),requestId:null});write(K.parts,arr);log(type==='in'?'دخول مخزون':'خروج مخزون','المخزن',p.id,`${p.name} — ${qty}`);location.reload()}}
document.addEventListener('DOMContentLoaded',()=>{stats();initCustomer();customerProfile();initDevice();deviceProfile();initRequest();requestProfile();initPart();partProfile();bindMovement()});
